# Generated by Django 3.2.10 on 2022-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('position', models.CharField(max_length=20, verbose_name='ポジション')),
                ('team', models.CharField(max_length=20, verbose_name='チーム')),
            ],
        ),
    ]
