# Generated by Django 3.2.10 on 2022-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstlist', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Septictank',
            fields=[
                ('cd', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='得意先コード')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('tel', models.CharField(max_length=13, verbose_name='TEL')),
            ],
        ),
    ]
