# Generated by Django 3.2.10 on 2022-06-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mstlist', '0003_septictank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sagyoCd', models.IntegerField(verbose_name='作業コード')),
                ('yDate', models.DateField(verbose_name='予定日')),
                ('yId', models.IntegerField(verbose_name='予定ID')),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstlist.septictank')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('cd', 'sagyoCd', 'yDate', 'yId'), name='unique_stock'),
        ),
    ]
