# Generated by Django 3.2.10 on 2022-06-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstlist', '0004_auto_20220630_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tCD',
            field=models.IntegerField(default=0, verbose_name='担当者コード'),
        ),
    ]
