# Generated by Django 3.2.10 on 2022-07-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mstlist', '0005_schedule_tcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sagyo',
            fields=[
                ('cd', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sagyoCd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstlist.sagyo'),
        ),
    ]
